//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsWebApp4.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HouseMoreEntities : DbContext
    {
        public HouseMoreEntities()
            : base("name=HouseMoreEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Project_Build> Project_Build { get; set; }
        public virtual DbSet<Project_House> Project_House { get; set; }
        public virtual DbSet<Project_HouseImg> Project_HouseImg { get; set; }
        public virtual DbSet<Project_MainImg> Project_MainImg { get; set; }
        public virtual DbSet<System_Company> System_Company { get; set; }
        public virtual DbSet<System_Project> System_Project { get; set; }
        public virtual DbSet<System_User> System_User { get; set; }
        public virtual DbSet<User_Cart> User_Cart { get; set; }
        public virtual DbSet<User_Collect> User_Collect { get; set; }
        public virtual DbSet<User_NotaryNo> User_NotaryNo { get; set; }
    }
}
