//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsWebApp4.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class System_Project
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_Project()
        {
            this.Project_Build = new HashSet<Project_Build>();
            this.Project_HouseImg = new HashSet<Project_HouseImg>();
            this.Project_MainImg = new HashSet<Project_MainImg>();
            this.User_NotaryNo = new HashSet<User_NotaryNo>();
        }

        [DataMember]
        public long ID { get; set; }
        [DataMember]
        public long CompanyID { get; set; }
        [DataMember]
        public string ProjectName { get; set; }
        [DataMember]
        public string ProjectShort { get; set; }
        [DataMember]
        public string ProjectAddress { get; set; }
        [DataMember]
        public string ProjectAgreement { get; set; }
        [DataMember]
        public string ProjectNotes { get; set; }
        [DataMember]
        public Nullable<int> ProjectStatus { get; set; }
        [DataMember]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DataMember]
        public Nullable<System.DateTime> EndDate { get; set; }
        [DataMember]
        public Nullable<int> OrderID { get; set; }
        [DataMember]
        public Nullable<int> Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_Build> Project_Build { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_HouseImg> Project_HouseImg { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Project_MainImg> Project_MainImg { get; set; }
        [DataMember]
        public virtual System_Company System_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_NotaryNo> User_NotaryNo { get; set; }
    }
}
