//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CsWebApp4.Models
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract]
    public partial class System_User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public System_User()
        {
            this.User_Cart = new HashSet<User_Cart>();
            this.User_Collect = new HashSet<User_Collect>();
            this.User_NotaryNo = new HashSet<User_NotaryNo>();
        }

        [DataMember]
        public long ID { get; set; }
        [DataMember]
        public long CompanyID { get; set; }
        [DataMember]
        public string UserName { get; set; }
        [DataMember]
        public string UserShort { get; set; }
        [DataMember]
        public Nullable<int> UserSex { get; set; }
        [DataMember]
        public string UserAddress { get; set; }
        [DataMember]
        public string UserAccont { get; set; }
        [DataMember]
        public string UserPasswd { get; set; }
        [DataMember]
        public Nullable<int> IsBindMobile { get; set; }
        [DataMember]
        public string UserMobile { get; set; }
        [DataMember]
        public Nullable<int> IsBindCard { get; set; }
        [DataMember]
        public string UserCard { get; set; }
        [DataMember]
        public string WxOpenId { get; set; }
        [DataMember]
        public string WxUnionid { get; set; }
        [DataMember]
        public Nullable<int> UserGrade { get; set; }
        [DataMember]
        public Nullable<System.DateTime> LoginDate { get; set; }
        [DataMember]
        public Nullable<int> OrderID { get; set; }
        [DataMember]
        public Nullable<int> Status { get; set; }

        [DataMember]
        public virtual System_Company System_Company { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Cart> User_Cart { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_Collect> User_Collect { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User_NotaryNo> User_NotaryNo { get; set; }
    }
}
